POST http://localhost:3002/users
Content-Type:application/json
{
    "firstName": "Sheldon Lee",
    "lastName": "Cooper",
    "email": "shelly@gmail.com",
    "password": "pa$$word"
}

POST http://localhost:3002/posts
Content-Type:application/json
{
    "title":"The Originals",
    "postType":"post",
    "postStatus":"scheduled",
    "content":"The origins of vampires, the firs family",
    "tags":["thriller","crime","romance"]
}


POST http://localhost:3002/meta-options
Content-Type:application/json
{
    "metaValue": "{\"sider\": true, \"verfied\": false}" 
}
