POST http://localhost:3002/auth/signin
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InJyYW1heWVua29vdGhyYXBhbGlAeWFob28uY29tIiwiaWF0IjoxNzM3MDMxMDg2LCJleHAiOjE3MzcwMzQ2ODYsImF1ZCI6ImxvY2FsaG9zdDogMzAwMiIsImlzcyI6ImxvY2FsaG9zdDogMzAwMiJ9.dsLlRdiwMtv0J1127rtweQni8_9rDYOsOgUr7MLkkm8
Content-Type: application/json
{
    "email": "rramayenkoothrapali@yahoo.com",
    "password": "pa$$word"
}

POST http://localhost:3002/auth/refreshToken
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InJyYW1heWVua29vdGhyYXBhbGlAeWFob28uY29tIiwiaWF0IjoxNzM3MDMxMDg2LCJleHAiOjE3MzcwMzQ2ODYsImF1ZCI6ImxvY2FsaG9zdDogMzAwMiIsImlzcyI6ImxvY2FsaG9zdDogMzAwMiJ9.dsLlRdiwMtv0J1127rtweQni8_9rDYOsOgUr7MLkkm8
Content-Type: application/json
{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJpYXQiOjE3MzczODU2NTcsImV4cCI6MTc0NDk4NTY1NywiYXVkIjoibG9jYWxob3N0OiAzMDAyIiwiaXNzIjoibG9jYWxob3N0OiAzMDAyIn0.8jXzb31yBvc3Nl6j4PUP2YhpPJuWpjxZXJF7fzUBqqA"
}